Created And Updated the reame.md file
upes-open/scientific-calculator pull request #1
Opened 2021-06-28 07:47 UTC by keshav2410garg

2021-06-28 18:42 UTC, akash2237778 requested changes
Not up to the mark! Please follow README guidlines use [this](https://github.com/upes-open/graph-generator/blob/main/README.md) as a reference. 
Documentation plays a very important role in every project. Specifically for `README.md` it becomes even more important as it's the first impression to the project. I hope you understand! :)

2021-06-28 18:42 UTC, akash2237778 commented on README.md
> +     git clone https://github.com/keshav2410garg/scientific-calculator.git
change URL for upstream i.e. https://github.com/upes-open/scientific-calculator

2021-06-30 06:25 UTC, akash2237778 requested changes
@khushboo-jakhmola can you please help us to improve this README? Language is not up to the mark. It doesn't sound technical README.

2021-06-30 06:25 UTC, akash2237778 commented on README.md
> +Ever wondered of making you own calculator that will be based your understading of the first language the you learned that is C++ and basic concepts of OOP's programming.
```suggestion
Ever wondered of making your own calculator that will be based on your understanding of the first language you learned that is C++ and basic concepts of OOP's programming.
```

2021-06-30 06:25 UTC, akash2237778 commented on README.md
> +So this repository focuses on making a calculator on C++ that will not enhance you C++ skills but also be based on object oriented and how these concepts can be modeled and replicated with
```suggestion
So this repository focuses on making a calculator using C++ that will not only enhance your C++ skills but also be based on object-oriented and how these concepts can be modeled and replicated with 
```

2021-06-30 06:25 UTC, akash2237778 commented on README.md
> +real world. Tis will also make use of basic data stuctures to store the results.
```suggestion
real world. This will also make use of basic data structures to store the results.
```

2021-07-01 12:11 UTC, khushboo-jakhmola requested changes
* Please change the case of the title to upper case.

Remove *overview* as a heading and start with the introduction to your project.
"Ever wondered what it takes to build your own calculator? Well, what if we tell you that all you need is a programming language like C++ and some basic knowledge of Object Oriented Programming. Still seems unreal? We'll walk you through it. This repository will not only brush up your knowledge of C++  but also educate you about concepts of OOPs and how they can be modeled and replicated with real world examples."

## FEATURES:
* The user will be able to perform both basic and scientific calculations using this calculator. For example:  "+" Addition, "-" Subtraction, "X" Multiplication,"/" Division and Trignometric operations.
* The calculator comes with an add on memory feature. With the help of this feature user can  store previous calculations and their results which can be referred to later for ease in calculations.
 

*REMOVE* how it works heading and its content -totally unnecessary 

*Few points to keep in mind:*
* Double check your spellings. 
* Highlight wherever its needed with bold and italics.
*  remove the background color as it distracts from the write up. 
* Maintain uniformity in your write up
@keshav2410garg 
@akash2237778

2021-07-03 17:52 UTC, akash2237778 commented
Looks good!

2021-07-03 17:57 UTC, khushboo-jakhmola reviewed
Looks good to me :)

2021-07-06 18:15 UTC, merged